[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
monitor-common = { path = "../monitor-common", features = ["user"] }
aya = { version = "0.13.1", default-features = false, features = [ "async_tokio" ] }
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["sync", "rt"] }
bytes = "1.10.1"
libc = "0.2.174"
tracing = "0.1.41"

[build-dependencies]
anyhow = { version = "1", default-features = false }
aya-build = { version = "0.1.2", default-features = false }
monitor-ebpf = { path = "../monitor-ebpf" }
