[workspace]
resolver = "3"
members = [
    "communicationcore",
    "communicationmanager",
    "capnp-schemas",
    "monitor",
    "monitor-common",
    "monitor-ebpf",
    "emulationcore",
    "controller",
    "kollaps-wasm",
]

# do not add monitor-ebpf to default-members or it won't compile
default-members = [
    "monitor",
    "monitor-common",
    "communicationcore",
    "communicationmanager",
    "capnp-schemas",
    "emulationcore",
    "controller",
    "kollaps-wasm",
]

# included by aya-rs project template
[profile.release.package.monitor-ebpf]
debug = 2
codegen-units = 1
